ARG ALPINE_VERSION=3.18

FROM node:lts-alpine${ALPINE_VERSION}
LABEL maintainer="dangquoctrung123@gmail.com"

ARG PNPM_VERSION=latest

RUN apk add --no-cache \
  gcompat libstdc++ zip jq sudo

## Install PNPM
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN touch /etc/profile.d/pnpmPath.sh && \
  echo "export PNPM_HOME=$PNPM_HOME" >> /etc/profile.d/pnpmPath.sh && \
  echo "export PATH=$PNPM_HOME:$PATH" >> /etc/profile.d/pnpmPath.sh && \
  source /etc/profile.d/pnpmPath.sh
# This will make the command re-run if theres a new pnpm version (prevents docker cache installing an older version)
ADD "https://api.github.com/repos/pnpm/pnpm/tags?per_page=1" latest_commit
RUN npx pnpm i -g pnpm@latest
RUN pnpm i -g @antfu/ni && echo 'defaultAgent=pnpm' > .nirc && echo 'globalAgent=pnpm' >> .nirc
##

## Install dev components (should be last in script)
RUN apk add --no-cache git less zsh curl

# Adding a simple command to change git remote connection from/to ssh/https
RUN touch /etc/profile.d/gitRemoteChanger.sh && \
  echo alias git-ssh=\'git remote set-url origin \"\$\(git remote get-url origin \| sed -E \'\\\'\'s,\^https://\(\[\^/\]\*\)/\(.\*\)\$,git@\\1:\\2,\'\\\'\'\)\"\' >> /etc/profile.d/gitRemoteChanger.sh && \
  echo alias git-https=\'git remote set-url origin \"\$\(git remote get-url origin \| sed -E \'\\\'\'s,\^git@\(\[\^:\]\*\):/\*\(.\*\)\$,https://\\1/\\2,\'\\\'\'\)\"\' >> /etc/profile.d/gitRemoteChanger.sh && \
  source /etc/profile.d/gitRemoteChanger.sh

RUN sh -c "$(wget -qO- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
  -x \
  -t https://github.com/spaceship-prompt/spaceship-prompt \
  -a 'SPACESHIP_USER_SHOW=false' \
  -a 'SPACESHIP_DIR_TRUNC_REPO=false' \
  -p command-not-found \
  -p git \
  -p history-substring-search \
  -p z \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions \
  -p https://github.com/zsh-users/zsh-syntax-highlighting

# Set zsh as the default shell
RUN sed -i 's/\/root:\/bin\/ash/\/root:\/bin\/zsh/g' /etc/passwd
CMD ["/bin/zsh", "--login"]
##
