## +aws: Building aws-cli
# Even though alpine 3.18+ have native aws-cli package, the self-built package have lower size and ensure latest version.
FROM namesmt/images-alpine:node-aws as builder
##


FROM namesmt/images-alpine:node-dev
LABEL maintainer="dangquoctrung123@gmail.com"

## +aws: Copy built aws-cli
COPY --from=builder /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
##
