name: Check for new release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
    - name: Check for new tags
      run: |
        ./.github/scripts/new_release_check.sh
